### ISSUE TITLE
Images associated with archival objects (from ArchivesSpace)

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#328]
[Copying below an email sent on 2021-Sept-29. This has more to do with ArchivesSpace than Blacklight, but it's probably still relevant.] 

I’m pleased to share promising developments concerning the display of digital images alongside YCBA objects described in ArchivesSpace. Much of this is a result of YUL’s ongoing development of its Archives at Yale interface, with changes to be implemented in the next month or so. Details below are based on a conversation this morning with Mark Custer.

1.	The revised interface will include the option to display images (and image sets) in a iiif viewer, as in [this example](https://puitestarchivesspace.library.yale.edu/repositories/2/archival_objects/2406133) in the Archives at Yale Test environment. (Ignore the mismatch between object and images). 

2.	In ArchivesSpace (the staff side), the above example is made possible via data as shown in the screenshot attached here. To conform to Yale’s implementation of digital objects, we will need three file URIs for each digital object:
a.	the iiif manifest
b.	a representative thumbnail
c.	the object in our Blacklight catalog

3.	The third URI requires that we have archival objects (from ArchivesSpace) represented in our Blacklight catalog, which of course we haven’t yet achieved. This adds motivation to do so.

4.	YUL is just beginning to implement (archival) digital objects on a wider scale. When it does so, it will generate the digital object records via scripts / syncing with the YUL digital collections system. While YCBA cannot make use of the same, Mark suggests that it should be possible for us to develop similar automated (or semi-automated) routines by adapting the existing YUL scripts. Mark would be happy to chat about this more with Eric et al, when the time comes. 

I think all of the above is quite positive, as our functional requirements are much clearer than before. 
![AS_digital_object_example](https://user-images.githubusercontent.com/7634899/135328724-64f31373-3fa7-413b-96c4-8c6bce236c2c.png)

**Comment by flapka** [comment]
@yulgit1 @mxgold Example implementation: https://puitestarchivesspace.library.yale.edu/repositories/2/archival_objects/2406133, using the "view.collections.yale.edu" URL.

Is it currently possible to point to the same with UV viewer?

The tangential benefit of that approach is that the pattern is the URL includes the object identifier, which would make batch edits easier later on (if we wanted to change the URL to collections.yale.edu).

For the thumbnail URL (see example above), is there a comparable pattern that could be implemented? This is less of a question/issue if we create the ArchivesSpace digital objects via an automated routine (following YUL's lead).

**Comment by flapka** [comment]
@yulgit1 @mxgold In discussion with Rachel and Molly, I sense agreement with Eric's concern that "it might be a better use of time to wait for a long term solution (like metadata cloud)."

Perhaps the easiest interim fix (for exposing images associated with archives) would be to show YCBA images in the Archives at Yale context, and nothing more. But that assumes an easy + viable method for making iiif manifests (for A@Y) without archives metadata in our Blacklight index. Is that indeed possible? Could we, for example, generate manifests from existing (skimpy) NetX metadata instead?

**Comment by yulgit1** [comment]
_from email thread: Re: Manifests for ras and arc without metadata_

Based on what Seong was saying, perhaps that something could be a spreadsheet with 3 columns (cmstype, cmsid, manifest label).  I could then create minimal json like:
 
{
  "unit": "YCBA",
  "cmsType": "ras",
  "cmsId": "123456",
  "metadata": [
    {
      "label": "Label",
      "value": "A label for an archival component"
    }
   ]
}
 
That would be delivered via activity streams, like what is currently being done from YCBA orb and obj.
 
This would depend on Francis or content owners to supply 3 column list, me to create the json and activity stream, Melissa/imaging to publish TMAN, and otherwise it sounds like this should just work the way ITS is set up.

**Comment by flapka** [comment]
Picking up on @yulgit1's comments above, the following procedures would govern iiif manifests for archival objects:

1. Apply the procedure to any NetX "pub" images that are published and have cmsType = ras 
2. For images meeting this scope specification, create separate iiif manifests for each distinct cmsID (cmsID = ASpace ID)
3. Map the NetX "Image Caption" field as value for iiif label. Where the "Image Caption" field is null, can we fill it in with "Image Courtesy YCBA" -- either by adding that text in NetX or by generating it on the fly?

Example 1 -- https://archives.yale.edu/repositories/2/archival_objects/2798372
* Includes two "pub" images
* label from NetX, for both images,  "Image Caption" = "John McHale Archive, ca. 1950-1978, Yale Center for British Art, Gift of Magda Cordell McHale"

Example 2 -- https://archives.yale.edu/repositories/2/archival_objects/3374
* includes one "pub" image
* "Image Caption" field is null in NetX. Can we generate "Image Courtesy YCBA"?

**Comment by yulgit1** [comment]
I've implemented activitystreams for ras per my comment 28 days ago above.

Here's the activity stream:
https://ycba-cds-iiif.s3.amazonaws.com/jsonpages/collection1.json

If you drill down to page13 and scroll to the bottom you will see the 98 ras objects just added:
https://ycba-cds-iiif.s3.amazonaws.com/jsonpages/page13.json

This creates an entry like:
```
{
      "type": "create",
      "object": {
        "id": "https://ycba-cds-iiif.s3.amazonaws.com/ycba/ras/1305.json",
        "type": "json",
        "context": "ras"
      },
      "endTime": "2021-12-17T20:11:17+00:00"
    },
```
With content like:
```
{
  "unit": "YCBA",
  "cmsType": "ras",
  "cmsId": "1305",
  "metadata": [
    {
      "label": "Label",
      "value": "Lady Mary Leighton (1799-1864), [Dancing crabs] from one of ten sketchbooks, 1824-1860, pen and black ink, Yale Center for British Art, Paul Mellon Fund"
    }
  ]
}
```
In NETX I just published ba-ras-1305-0002-pub as"PPP 4096 0"

Seong writes:

"Currently, a manifest is built only if there exists a record in the objects table of cds2 database, and object records are created only when the metadata comes from the activity stream.
 
Assuming the ras and arc manfiests will require the same key (unitcode + cmstype + cmsid), an easy way to do it is to instruct the system to create an object record if there's none for that unitcode + cmstype + cmsid already. The only requirement missing is the label for the manifest then."

So the combination of the metadata from the activitystream and the published of ba-ras-1305-0002-pub should create a manifest.

**Comment by flapka** [comment]
@yulgit1 @Lcallery All of the above sounds good to me. Thanks for moving this forward!

I see that a manifest exists for this archival object: https://view.collections.yale.edu/m3/?manifest=https://manifests.collections.yale.edu/ycba/ras/1305

But not any (?) of the others, for example the next one: https://view.collections.yale.edu/m3/?manifest=https://manifests.collections.yale.edu/ycba/ras/1311

Did you do something different with the first?

**Comment by yulgit1** [comment]
@flapka At least 2 things have to happen to produce the manifest: (1) publish the metadata (done). (2) publish the image in NETX (done for 1305 only, as "PPP 4096 0").  @flapka I'm not sure if you were ever introduced to the NETX CDS2 flags and publishing.  If not, I can explain.

Also, the SQL to generate the metadata for the activitystream specifically is:

```
"select cmsid, max(imagecaption) as label from assets "\
    "where unitcode = 'YCBA' and cmstype = 'ras' and imagecaption is not null "\
    "and imagecaption != 'Image Courtesy YCBA' "\
    "group by cmsid order by cmsid"
```

Thereby excluding some of the ras ids with empty or default captions. This can change to whatever really makes sense.

**Comment by flapka** [comment]
For ras:1305, here's how the asset could display in AS (this link is to test). We could use UV instead of Mirador:
https://puitestarchivesspace.library.yale.edu/repositories/2/archival_objects/1305

Below is the digital object record in ArchivesSpace:
![FireShot Capture 092 - ArchivesSpace - Digital Objects - Album - Edit_ - testarchivesspace library yale edu](https://user-images.githubusercontent.com/7634899/146822450-1b03c9c7-0730-4f88-b195-ec16b1564d0a.png)

**Comment by flapka** [comment]
We're getting much closer, but we still have these issues to resolve:

1. [YUL]: The ArchivesSpace update enabling a iiif viewer is not yet in production. Hopefully this will happen early in the new year.
2. [mostly @flapka @Lcallery  ]: Do we want to explore batch methods for creating digital objects, or (at the beginning at least) manual?
3. [@yulgit1 ]: The AS system requires a thumbnail URL, as illustrated above. For the ras:1305 example, I figured it out by inspecting the HTML associated with the object in the iiif viewer. Not a speedy process. Is there an easier way?
4. [@Lcallery @mxgold @annabozz ]: Should the "caption" in the AS digital object -- where I put "test caption" in our example -- be the same as the image caption in NetX? This displays beneath a thumbnail (with limited space), so I think we want something short.
5. [@Lcallery @mxgold @annabozz ]: If I understand @yulgit1's message above, we need to generate image captions for these archival objects before a manifest can be created?

**Comment by yulgit1** [comment]
(3)
For the thumbnail, the easiest route would be to check the manifest for the default image's  (first image) thumbnail https://manifests.collections.yale.edu/ycba/ras/1305

(5)
The manifest metadata activity stream query that finds the ras object ids to include currently skips those without image captions, that can be tweaked.  But best practice in manifest creation would be to add image captions when publishing images in NETX to CDS2.

**Comment by yulgit1** [comment]
Just a note that I'm going to change the metadata query from:

```
"select cmsid, max(imagecaption) as label from assets "\
    "where unitcode = 'YCBA' and cmstype = 'ras' and imagecaption is not null "\
    "and imagecaption != 'Image Courtesy YCBA' "\
    "group by cmsid order by cmsid"
```
to
```
select cmsid,cmstype,imagecaption as label from assets 
where unitcode = 'YCBA' and cmstype in('ras','arc') and cdsprimary = 1 
```

The first query gets max(imagecaption) for all the rows with a certain cmsid, which is the last alphabetical.  The second query gets the imagecaption of the primary image.  This makes sense as the manifest label is more likely to be the primary image caption that whatever imagecaption happens to sort to last.  Of course the cds primary has to be set, but if were publishing images it should be.  The query won't have a join so should be quicker.

It happens to be  that all the primary images now for 'ras' have 'Image Courtesy 'YCBA' so I'll will change the NETX cdsprimary of one of 1305 to test.

**Comment by mxgold** [comment]
4. I agree it should match the NetX image caption
5. We would have, but will no longer, if I understand @yulgit1’s subsequent changes to the metadata query correctly. But will be on us to populate image caption as a best practice.

From: Francis Lapka ***@***.***>
Reply-To: ycba-cia/blacklight-collections2 ***@***.***>
Date: Monday, December 20, 2021 at 2:45 PM
To: ycba-cia/blacklight-collections2 ***@***.***>
Cc: Melissa Fournier ***@***.***>, Mention ***@***.***>
Subject: Re: [ycba-cia/blacklight-collections2] Images associated with archival objects (from ArchivesSpace) (#328)


We're getting much closer, but we still have these issues to resolve:

  1.  [YUL]: The ArchivesSpace update enabling a iiif viewer is not yet in production. Hopefully this will happen early in the new year.
  2.  [mostly @flapka<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflapka&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263364896489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YgYr%2FbU0eT6Gd0Bd6EMR1ZCphy1G%2FOB2P1JRunqJrDI%3D&reserved=0> @Lcallery<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLcallery&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263364896489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XZzXAokjjUX8Hky3DkK9KQdYob4waumYAxrH%2Bcq1oFw%3D&reserved=0> ]: Do we want to explore batch methods for creating digital objects, or (at the beginning at least) manual?
  3.  ***@***.***<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyulgit1&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263364896489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dQ1KWjzSkQSFMgqrBaPlfU3IE5vQj1tL%2BrjLsWbQhTQ%3D&reserved=0> ]: The AS system requires a thumbnail URL, as illustrated above. For the ras:1305 example, I figured it out by inspecting the HTML associated with the object in the iiif viewer. Not a speedy process. Is there an easier way?
  4.  ***@***.***<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLcallery&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nly%2BpaGrTg%2FOTga9%2FvyTn%2Ffx2xht0Xg5mjeggVJZAnw%3D&reserved=0> @mxgold<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmxgold&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BJ%2BDXUIH1xu8HJ%2F5tMUbULvHrlBLIoX4iGbXmFpvpbQ%3D&reserved=0> @annabozz<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fannabozz&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WoCINs10TU0xB0XVneDYW3H5012WdUvxqoUXx2Ov8sA%3D&reserved=0> ]: Should the "caption" in the AS digital object -- where I put "test caption" in our example -- be the same as the image caption in NetX? This displays beneath a thumbnail (with limited space), so I think we want something short.
  5.  ***@***.***<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLcallery&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nly%2BpaGrTg%2FOTga9%2FvyTn%2Ffx2xht0Xg5mjeggVJZAnw%3D&reserved=0> @mxgold<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmxgold&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BJ%2BDXUIH1xu8HJ%2F5tMUbULvHrlBLIoX4iGbXmFpvpbQ%3D&reserved=0> @annabozz<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fannabozz&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WoCINs10TU0xB0XVneDYW3H5012WdUvxqoUXx2Ov8sA%3D&reserved=0> ]: If I understand @yulgit1<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyulgit1&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Fq9QGEkCzhITD15UNHZ0z8nYfcQfxcfMA6eF8%2B0CLKA%3D&reserved=0>'s message above, we need to generate image captions for these archival objects before a manifest can be created?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fycba-cia%2Fblacklight-collections2%2Fissues%2F328%23issuecomment-998219646&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HqQItffc6%2B%2FGVaMwRjUMzWXRlThbBV3PozDd7826y8M%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIWY3IAPJE5BA2MDGBUXRMTUR6BVVANCNFSM5FARPR2Q&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=miy4zmTFTlVivo9cpQ9DieHlislSQWKdbbXBhB02k7g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmelissa.fournier%40yale.edu%7C01015f886b244c9cea0d08d9c3f1483d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637756263365052721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SeiurFggcBD6B0Q9pL7JE4Gjx1m5kZnho23Uy1C%2Fh1E%3D&reserved=0>.

**Comment by yulgit1** [comment]
Settled on this query to provide manifest metadata for the activity stream:
https://ycba-cds-iiif.s3.amazonaws.com/jsonpages/collection1.json
```
"select cmsid,cmstype,imagecaption as label from assets " \
    "where unitcode = 'YCBA' and cmstype in('ras','arc') and cdsprimary = 1 " \
    "and imagecaption is not null and imagecaption != '' and imagecaption != 'Image Courtesy YCBA'"
```
So as a round-trip example, to publish an arc/ras manifest one must:
(1)
Have arc and ras images in TMAN/NETX
(2)
have at least 1 image of a cmstype:cmsid (ex: ras:1305) set with with cdsprimary =1 in TMAN/NETX
(3)
have the imagecaption for the image with cdsprimary=1 exist and not equal to the default 'Image Courtesy YCBA'" as set in TMAN/NETX
(4)
publish by setting the CDS2 fields:
CDS Access JPEG
CDS Access Master
CDS Access TIFF  
CDS Maxsize JPEG
CDS Maxsize TIFF

**Comment by mxgold** [comment]
Thanks @yulgit1 .  So, as it currently stands, we will be required to select a primary image and provide a non-default image caption for that primary image in order to publish an arc/ras manifest.

**Comment by edgartdata** [comment]
@mxgold Could this solution be adopted to publish the photo of Paul Mellon next to the Dartrey bust https://collections.britishart.yale.edu/catalog/tms:1478 be used to publish it as an AS item?

**Comment by edgartdata** [comment]
@mxgold I understand from Rachel that there might not be a full finding aids available for this specific photo yet?

**Comment by mxgold** [comment]
Could be, but I do think it's likely that a copy of the photo is in this collection, which does have an ArchiveSpace record and full finding aid: https://archives.yale.edu/repositories/3/resources/5545#

**Comment by flapka** [comment]
Unrelated to the Feb 15 comments above, but an update on this thread all the same: YUL's implementation of the new version of ArchivesSpace (capable of serving iiif images) is delayed. As of yesterday, Mark Custer estimates (/hopes for) implementation "before April Fool's Day."

**Comment by flapka** [comment]
@Lcallery @mollyED @yulgit1 @edgartdata @mxgold @rchatalbash -- Based on recent developments, we might be very close to having everything we need to publish images for archival material in ArchivesSpace. Here's an example in *production* Archives at Yale: https://archives.yale.edu/repositories/2/archival_objects/1305

Until three weeks ago what you see there was possible only in test A@Y. 

If we were happy to create AS digital objects on a one-by-one basis, we have everything we need to move forward now. But a bulk method is probably more sensible. I have this from my notes in September 2021:

> YUL is just beginning to implement (archival) digital objects on a wider scale. When it does so, it will generate the digital object records via scripts / syncing with the YUL digital collections system. While YCBA cannot make use of the same, Mark suggests that it should be possible for us to develop similar automated (or semi-automated) routines by adapting the existing YUL scripts. Mark would be happy to chat about this more with Eric et al, when the time comes. 

Do we agree that a scripted method is preferred? If so, shall we arrange a meeting with Mark (Custer)?

Screenshot of digital object in the AS application:
![do-screenshot](https://user-images.githubusercontent.com/7634899/164259427-70140e31-2915-48d8-983b-4ff5013bbcc3.jpg)

**Comment by mollyED** [comment]
Many thanks for this update @flapka--I agree that a scripted method would be preferred, but it might be helpful to think through the basics of the workflow regardless. I'm wondering whether there's any [manual] prep work necessary to enable the automation.

**Comment by yulgit1** [comment]
++ next steps with Mark, soon (not too soon)

**Comment by edgartdata** [comment]
@yulgit1 Mark Custer I assume?

**Comment by edgartdata** [comment]
@flapka @jessquag It looks like the examples that used to have images back in 2021 don't anymore?
https://archives.yale.edu/repositories/2/archival_objects/2798372
https://archives.yale.edu/repositories/2/archival_objects/3374

**Comment by flapka** [comment]
@edgartdata Correct, those two examples were fleeting. This is the only one currently out there, and it doesn't get everything right: https://archives.yale.edu/repositories/2/digital_objects/177515
